/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.SwingConstants;

/**
 *
 * @author uni
 */
public class MainI extends javax.swing.JFrame {

    /**
     * Creates new form MainI
     */
    public MainI() {
        initComponents();
        ImageIcon iconoOriginal = new ImageIcon(getClass().getResource("/Imagenes/APPLE.png"));
        Image imagenRedimensionada = iconoOriginal.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH); // Cambia el tamaño según necesites
        ImageIcon iconoRedimensionado = new ImageIcon(imagenRedimensionada);
        Apple.setIcon(iconoRedimensionado);
        Apple.setText("APPLE");
        Apple.setVerticalTextPosition(SwingConstants.BOTTOM);
        Apple.setHorizontalTextPosition(SwingConstants.CENTER);
        Apple.setPreferredSize(new Dimension(100, 80));
        ImageIcon iconoOriginal2 = new ImageIcon(getClass().getResource("/Imagenes/DELL.png"));
        Image imagenRedimensionada2 = iconoOriginal2.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH); // Cambia el tamaño según necesites
        ImageIcon iconoRedimensionado2 = new ImageIcon(imagenRedimensionada2);
        Dell.setIcon(iconoRedimensionado2);
        Dell.setText("DELL");
        Dell.setVerticalTextPosition(SwingConstants.BOTTOM);
        Dell.setHorizontalTextPosition(SwingConstants.CENTER);
        Dell.setPreferredSize(new Dimension(100, 80));
        ImageIcon fondo11 = new ImageIcon(getClass().getResource("/Imagenes/VS.jpg"));
        Image imagenRedimensionada3 = fondo11.getImage().getScaledInstance(Panel1.getWidth(), Panel1.getHeight(), Image.SCALE_SMOOTH); // Cambia el tamaño según necesites
        ImageIcon iconoRedimensionado3 = new ImageIcon(imagenRedimensionada3);
        fondo.setIcon(iconoRedimensionado3);
        

     
        

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        Apple = new javax.swing.JButton();
        Dell = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Apple.setText("jButton1");
        Apple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppleActionPerformed(evt);
            }
        });
        Panel1.add(Apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        Dell.setText("jButton1");
        Panel1.add(Dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 310));
        Panel1.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AppleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppleActionPerformed
       
        
    }//GEN-LAST:event_AppleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apple;
    private javax.swing.JButton Dell;
    private javax.swing.JPanel Panel1;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo2;
    // End of variables declaration//GEN-END:variables
}
